[tool.pytest]
markers = ["slow"]

[tool.pixi.workspace]
name = "examples"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
python = "3.14.*"
numpy = ">=2.4.1,<3"
requests = ">=2.32.5,<3"
astropy = ">=7.2.0,<8"
pytest = "9.*"
pytest-cov = "*"
